/*
 * Copyright (c) 2026 Lunabee Studio
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package studio.lunabee.monitoring.core

import kotlin.time.Instant
import kotlin.time.Duration
import kotlin.uuid.Uuid

/**
 * Data class that represents a request content.
 * @param id id of the request, generated by the library.
 * @param host base url of the request (without path/query params).
 * @param methodName method name as [String] (ex: GET, POST, etc).
 * @param statusCode status response code (200, 404, ect).
 * @param sendingAt time when the request was sent.
 * @param duration duration of the request.
 * @param path path of the request (if any), like /users/123.
 * @param queryParams query params of the request (if any), like ?name=John&surname=Doe.
 * @param outgoingPayload sent payload of the request.
 * @param incomingPayload received payload of the request.
 */
data class LBRequest(
    val id: Uuid,
    val host: String,
    val methodName: String,
    val statusCode: Int,
    val sendingAt: Instant,
    val duration: Duration,
    val path: String?,
    val queryParams: String?,
    val outgoingPayload: LBPayload?,
    val incomingPayload: LBPayload?,
)
